IF
  Global("NTotSCSpawn","AR3900",0)
THEN
  RESPONSE #100
    CreateCreature("NTNATALK",[2248.240],3)
    CreateCreature("NTELKA",[2145.205],4)
    SetGlobal("NTotSCSpawn","AR3900",1)
END

IF
  Global("NTotSCspawn","AR3900",1)
  OR(2)
  GlobalGT("DMWWC3Assassin","GLOBAL",0)
  !Exists("LAMALH")
THEN
  RESPONSE #100
    ActionOverride("NTNATALK",DestroySelf())
    ActionOverride("NTELKA",DestroySelf())
    SetGlobal("NTotSCSpawn","AR3900",2)
END